//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tvshows.Strings {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("tvshows.Strings.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CollectionPageTitle {
            get {
                return ResourceManager.GetString("CollectionPageTitle", resourceCulture);
            }
        }
        
        public static string CollectionPageEmptyStateMessage {
            get {
                return ResourceManager.GetString("CollectionPageEmptyStateMessage", resourceCulture);
            }
        }
        
        public static string DetailsPagePremieredLabel {
            get {
                return ResourceManager.GetString("DetailsPagePremieredLabel", resourceCulture);
            }
        }
        
        public static string DetailsPageNumberOfEpisodesLabel {
            get {
                return ResourceManager.GetString("DetailsPageNumberOfEpisodesLabel", resourceCulture);
            }
        }
        
        public static string DetailsPageEpisodesLabel {
            get {
                return ResourceManager.GetString("DetailsPageEpisodesLabel", resourceCulture);
            }
        }
        
        public static string DetailsPageRateLabel {
            get {
                return ResourceManager.GetString("DetailsPageRateLabel", resourceCulture);
            }
        }
        
        public static string DetailsPageStatusLabel {
            get {
                return ResourceManager.GetString("DetailsPageStatusLabel", resourceCulture);
            }
        }
        
        public static string DetailsPageCastingHeader {
            get {
                return ResourceManager.GetString("DetailsPageCastingHeader", resourceCulture);
            }
        }
        
        public static string DetailsPageEpisodeHeader {
            get {
                return ResourceManager.GetString("DetailsPageEpisodeHeader", resourceCulture);
            }
        }
        
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        public static string SearchPageResearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPageResearchPlaceholder", resourceCulture);
            }
        }
        
        public static string CastingViewEmptyStateLabel {
            get {
                return ResourceManager.GetString("CastingViewEmptyStateLabel", resourceCulture);
            }
        }
    }
}
